name: S3 Buckets List

on:
  workflow_dispatch:          # Trigger manually
  push:                      
    branches:
      - main

jobs:
  jobid1:
    runs-on: self-hosted       

    steps:

      - name: AWS - Actions-user-Security-Credentials
        run: |     
          export AWS_ACCESS_KEY=${{ secrets.ACCESS_KEY_ID }}
          export SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY_ID }}
          export AWS_DEFAULT_REGION=${{ secrets.REGION}}
          aws s3 ls
